"""Render walt.id issuer-api2 configuration for one credential issuer.

Writes the two files the service reads:

* `issuer2-profiles.conf`  -- the profile: private JWK, `issuerDid`, `x5Chain`, claims.
* `credential-issuer-metadata.conf` -- the credential configuration the offer refers to.

The exact syntax was established by the spike recorded in record/NOTES-waltid.md.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from jwkexport import load_private_key, private_jwk

PROFILE_TEMPLATE = '''# Generated by src/issuer/render_profile.py -- do not edit by hand.
#
# The signing key below was certified by the Demo National Issuing CA, which chains to the
# Demo National Root CA. The root is deliberately NOT in x5Chain: it is the verifier's trust
# anchor. walt.id's own shipped configuration says the same thing -- "the external trust
# anchor is configured separately and MUST NOT be embedded here".

issuerKey = {{
  type = "jwk"
  jwk = {{
    kty = "EC"
    crv = "P-256"
    d = "{d}"
    x = "{x}"
    y = "{y}"
  }}
}}

issuerDid = "{did}"

x5Chain = [
  """{leaf}""",
  """{issuing_ca}"""
]

profiles = {{
  {profile_id} = {{
    name = "{credential_type}"
    credentialConfigurationId = "{configuration_id}"
    issuerKey = ${{issuerKey}}
    issuerDid = ${{issuerDid}}
    x5Chain = ${{x5Chain}}
    credentialData = {{
      "@context" = ["https://www.w3.org/ns/credentials/v2"]
      "id" = "THIS WILL BE REPLACED WITH DYNAMIC DATA FUNCTION"
      "type" = ["VerifiableCredential", "{credential_type}"]
      "issuer" = {{
        "type" = ["Profile"]
        "id" = "THIS WILL BE REPLACED WITH DYNAMIC DATA FUNCTION"
        "name" = "{organisation}"
      }}
      "validFrom" = "THIS WILL BE REPLACED WITH DYNAMIC DATA FUNCTION"
      "credentialSubject" = {{
        "id" = "THIS WILL BE REPLACED WITH DYNAMIC DATA FUNCTION"
        "operatorName" = "Demonstration Holder"
        "licenceNumber" = "OP-2026-0001"
        "accreditedBy" = "{organisation}"
      }}
    }}
    mapping = {{
      "id" = "<uuid>"
      "issuer" = {{
        "id" = "<issuerDid>"
      }}
      "credentialSubject" = {{
        "id" = "<subjectDid>"
      }}
      "validFrom" = "<timestamp>"
    }}
  }}
}}
'''

METADATA_TEMPLATE = '''# Generated by src/issuer/render_profile.py -- do not edit by hand.

issuerDisplay = [
  {{
    name = "{organisation}"
    locale = "en-GB"
  }}
]

credentialConfigurations = {{
  "{configuration_id}" = {{
    format = "jwt_vc_json"
    scope = "{configuration_id}"
    credential_signing_alg_values_supported = ["ES256"]
    cryptographic_binding_methods_supported = ["jwk", "did:key", "did:jwk", "did:web"]
    proof_types_supported = {{
      jwt = {{
        proof_signing_alg_values_supported = ["ES256"]
      }}
    }}
    credential_definition = {{
      type = ["VerifiableCredential", "{credential_type}"]
    }}
  }}
}}
'''

SERVICE_TEMPLATE = '''# Generated by src/issuer/render_profile.py -- do not edit by hand.
#
# baseUrl is echoed into the issuer metadata, the credential offer URI and the proof `aud`,
# so it must be the URL the holder actually reaches.

baseUrl = "{base_url}"

ciTokenKey = """{{"type":"jwk","jwk":{token_jwk}}}"""

credentialEncryptionKey = """{{"type":"jwk","jwk":{encryption_jwk}}}"""

clientAuthenticationConfig {{
  supportedMethods = [
    {{
      type = "preauth-anonymous"
    }}
  ]
}}
'''


def _pem(path: str | Path) -> str:
    return Path(path).read_text().strip()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--did", required=True)
    parser.add_argument("--key", required=True)
    parser.add_argument("--leaf", required=True)
    parser.add_argument("--issuing-ca", required=True)
    parser.add_argument("--out", required=True, help="the config directory to write")
    parser.add_argument("--base-url", required=True)
    parser.add_argument("--profile-id", default="accreditedOperatorCredential")
    parser.add_argument("--credential-type", default="AccreditedOperatorCredential")
    parser.add_argument("--organisation", default="Demo National Operator Registry")
    args = parser.parse_args()

    jwk = private_jwk(load_private_key(args.key))
    configuration_id = f"{args.credential_type}_jwt_vc_json"
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    (out / "issuer2-profiles.conf").write_text(PROFILE_TEMPLATE.format(
        d=jwk["d"], x=jwk["x"], y=jwk["y"], did=args.did,
        leaf=_pem(args.leaf), issuing_ca=_pem(args.issuing_ca),
        profile_id=args.profile_id, credential_type=args.credential_type,
        configuration_id=configuration_id, organisation=args.organisation,
    ))
    (out / "credential-issuer-metadata.conf").write_text(METADATA_TEMPLATE.format(
        configuration_id=configuration_id, credential_type=args.credential_type,
        organisation=args.organisation,
    ))

    # Service keys are internal to issuer-api2 (they sign its own access tokens) and are
    # unrelated to credential signing, so they are generated here rather than certified.
    from cryptography.hazmat.primitives.asymmetric import ec

    from jwkexport import private_jwk as to_private_jwk

    token = to_private_jwk(ec.generate_private_key(ec.SECP256R1()))
    encryption = to_private_jwk(ec.generate_private_key(ec.SECP256R1()))
    encryption["kid"] = "issuer2-credential-encryption-key"

    (out / "issuer-service.conf").write_text(SERVICE_TEMPLATE.format(
        base_url=args.base_url,
        token_jwk=json.dumps(token, separators=(",", ":")),
        encryption_jwk=json.dumps(encryption, separators=(",", ":")),
    ))
    (out / "web.conf").write_text('webHost = "0.0.0.0"\nwebPort = "7005"\n')
    (out / "_features.conf").write_text("enabledFeatures = []\ndisabledFeatures = []\n")
    (out / "persistence.conf").write_text('type = "in-memory"\n')

    print(f"{out}: profile {args.profile_id}, configuration {configuration_id}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
