#!/usr/bin/env bash
# Render the recordings as GIFs small enough to commit, and put them in docs/media/.
#
# Why GIFs and why committed: a reader should be able to watch the demonstration from the
# README without cloning anything or running anything. GitHub renders a repository-relative
# GIF inline and plays it; an .mp4 at a repository path is only a download link. The .cast and
# .mp4 files stay out of version control -- they are regenerated by record/record.sh.
#
# The settings below trade frame rate for size. `--fps-cap 6` and a short `--idle-time-limit`
# are what bring a multi-megabyte capture down to something reasonable to commit; the build
# recording is additionally sped up, because nobody needs to watch RSA key generation at
# normal pace.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE="${RECORDER_IMAGE:-pki-in-did/recorder}"
OUT="$REPO/docs/media"
CASTS="$REPO/recordings"

mkdir -p "$OUT"
[[ -d "$CASTS" ]] || { echo "no recordings/ yet -- run record/record.sh all" >&2; exit 1; }

render() {
  local name="$1"; shift
  local cast="$CASTS/$name.cast"
  [[ -f "$cast" ]] || { echo "  skip $name (no cast)"; return 0; }
  docker run --rm -u "$(id -u):$(id -g)" \
    -v "$REPO:$REPO" -w "$REPO" --entrypoint agg "$IMAGE" \
    --theme asciinema --font-size 12 --fps-cap 6 --idle-time-limit 0.7 "$@" \
    "$cast" "$OUT/$name.gif" >/dev/null 2>&1
  printf '  %-26s %sK\n' "$name.gif" "$(( $(stat -c%s "$OUT/$name.gif") / 1024 ))"
}

echo "rendering GIFs for the README into docs/media/"
# The five demonstration parts at normal pace: they are short and every line matters.
for part in part1-happy-online part2-happy-offline part3-revocation-online \
            part4-revocation-offline part5-the-gap; do
  render "$part"
done
# The build is long and mostly waiting on key generation, so it runs at triple speed.
render part0-setup --speed 3

printf '\n  total %sK in docs/media/\n' "$(du -sk "$OUT" | cut -f1)"
